version: '3.8'

services:
  strapi:
    build: ./strapi
    user: "0:0"
    container_name: reqspoural_backend
    env_file: 
      - ./strapi/.env
    volumes:
      - ./strapi:/opt/app
    ports:
      - "1337:1337"
  
  next: 
    build: ./next
    user: "0:0"
    container_name: reqspoural_frontend
    env_file: 
      - ./next/.env
    volumes:
      - ./next:/app
    ports:
      - 3000:3000

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - next