version: '3.8'

services:
  strapi:
    build: ./strapi
    env_file: 
      - ./strapi/.env
    volumes:
      - ./strapi:/opt/app
    ports:
      - "1337:1337"
  
  next: 
    build: 
      context: ./next
    volumes:
      - ./next:/app
    env_file: 
      - ./next/.env
    ports:
      - 3000:3000

  nginx:
    build: 
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - strapi
      - next