name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup SSH and Run Scripts on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/applications/RequestSpoUral
            git pull
            find scripts/ -type f -iname "*.sh" -exec chmod +x {} \;
            if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'next/'; then
              echo "Reloading next..."
              sh scripts/reload_front.sh
            fi
            if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'strapi/'; then
              echo "Reloading strapi..."
              sh scripts/reload_back.sh
            fi
            if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'nginx/'; then
              echo "Reloading nginx..."
              sh scripts/reload_nginx.sh
            fi
            sh scripts/clean_up.sh